---
- hosts: all
  become: yes
  tasks:
   - name: i want to install git
     apt:
       name: git
       state: prsent
   - name: i want install tree
     apt:
       name: tree
       state: prsent
